/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function encode(addr: string): void
export interface HexAddress {
  hexAddress: string
  netId: number
  type: string
}
export declare function decode(base32Address: string): HexAddress
