/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const MAIN_NET_ID: number
export const TEST_NET_ID: number
export declare function encode(addr: string): void
export interface DecodeResult {
  hexAddress: string
  netId: number
  type: string
}
export declare function decode(base32Address: string): DecodeResult
